### PR TITLE
Support unix socket for nsqd connection

### PR DESCRIPTION
**Pull request by telepenin**
Example to create reader:
```
    reader = nsq.Reader(
            topic="nsq-test-writer", channel="test-ch", message_handler=message_handler,
            lookupd_connect_timeout=10, requeue_delay=10, 
            nsqd_tcp_addresses=['/var/run/nsqd.sock'], max_in_flight=5, snappy=True
    )

```
and writer
```
nsq.Writer(nsqd_tcp_addresses=['/var/run/nsqd.sock'], snappy=True)
```
with connection to nsqd via unix sockets.

### CODE REVIEW

**Review by iseletsk — COMMENTED** [review]
are you sure you want to implement compression (even if it is snappy) over the UNIX socket?
It kind of makes sense over the network, but over IPC - which is just moving bytes in memory - it might not be worth it at all.
Did you try the performance?

**Review by iseletsk — APPROVED** [review]
Actually, never mind, these is just tests. Looks good to me.

**Comment by telepenin** [comment]
@iseletsk client can choose using snappy or not. Server by default support snappy compression.

**Review by moredure — APPROVED** [review]
LGTM

**Pull request merged**
